#embed_assets: on
package_assets: always
compress_assets: off
template_extension: html.handlebars
template_function: "Handlebars.compile"

javascripts:
  app:
    - app/assets/javascripts/vendor/jquery.min.js
    - app/assets/javascripts/vendor/jquery-ui.min.js
    - app/assets/javascripts/vendor/rails.js
    - app/assets/javascripts/vendor/underscore-min.js
    - app/assets/javascripts/vendor/backbone-min.js
    - app/assets/javascripts/vendor/*.js
    - tmp/coffeescripts/boot.js
    - tmp/coffeescripts/**/*.js
    - app/assets/javascripts/views/*.html.handlebars
